export type LanguageCode = "en" | "de" | "fr" | "es" | "it" | "pt" | "ar" | "ja";

export const supportedLanguages: LanguageCode[] = ["en", "de", "fr", "es", "it", "pt", "ar", "ja"];

type TranslationSet = Partial<Record<LanguageCode, string>>;

const phraseTable: Record<string, TranslationSet> = {
  "Home": { de: "Startseite", fr: "Accueil", es: "Inicio", it: "Home", pt: "Inicio", ar: "Home", ja: "Home" },
  "Products": { de: "Produkte", fr: "Produits", es: "Productos", it: "Prodotti", pt: "Produtos", ar: "Products", ja: "Products" },
  "Custom Process": { de: "Anpassungsprozess", fr: "Processus sur mesure", es: "Proceso personalizado", it: "Processo personalizzato", pt: "Processo personalizado", ar: "Custom Process", ja: "Custom Process" },
  "Applications": { de: "Anwendungen", fr: "Applications", es: "Aplicaciones", it: "Applicazioni", pt: "Aplicacoes", ar: "Applications", ja: "Applications" },
  "About Us": { de: "Uber uns", fr: "A propos", es: "Sobre nosotros", it: "Chi siamo", pt: "Sobre nos", ar: "About Us", ja: "About Us" },
  "Blog": { de: "Blog", fr: "Blog", es: "Blog", it: "Blog", pt: "Blog", ar: "Blog", ja: "Blog" },
  "Contact": { de: "Kontakt", fr: "Contact", es: "Contacto", it: "Contatto", pt: "Contato", ar: "Contact", ja: "Contact" },
  "Get a Quote": { de: "Angebot anfragen", fr: "Demander un devis", es: "Solicitar cotizacion", it: "Richiedi un preventivo", pt: "Solicitar orcamento", ar: "Get a Quote", ja: "Get a Quote" },
  "View Products": { de: "Produkte ansehen", fr: "Voir les produits", es: "Ver productos", it: "Vedi prodotti", pt: "Ver produtos", ar: "View Products", ja: "View Products" },
  "View all products": { de: "Alle Produkte ansehen", fr: "Voir tous les produits", es: "Ver todos los productos", it: "Vedi tutti i prodotti", pt: "Ver todos os produtos", ar: "View all products", ja: "View all products" },
  "View All Products": { de: "Alle Produkte ansehen", fr: "Voir tous les produits", es: "Ver todos los productos", it: "Vedi tutti i prodotti", pt: "Ver todos os produtos", ar: "View All Products", ja: "View All Products" },
  "View details": { de: "Details ansehen", fr: "Voir les details", es: "Ver detalles", it: "Vedi dettagli", pt: "Ver detalhes", ar: "View details", ja: "View details" },
  "Product Categories": { de: "Produktkategorien", fr: "Categories de produits", es: "Categorias de productos", it: "Categorie prodotto", pt: "Categorias de produtos", ar: "Product Categories", ja: "Product Categories" },
  "Custom metal crafts for B2B buyers": { de: "Individuelle Metallwaren fur B2B-Kaufer", fr: "Objets metalliques personnalises pour acheteurs B2B", es: "Artesanias metalicas personalizadas para compradores B2B", it: "Articoli metallici personalizzati per buyer B2B", pt: "Brindes metalicos personalizados para compradores B2B", ar: "Custom metal crafts for B2B buyers", ja: "Custom metal crafts for B2B buyers" },
  "Select the product type that matches your artwork, campaign, event or retail program.": { de: "Wahlen Sie den Produkttyp, der zu Artwork, Kampagne, Event oder Einzelhandelsprogramm passt.", fr: "Choisissez le type de produit adapte a votre visuel, campagne, evenement ou programme retail.", es: "Seleccione el tipo de producto que encaje con su arte, campana, evento o programa retail.", it: "Seleziona il prodotto adatto al tuo artwork, campagna, evento o programma retail.", pt: "Selecione o tipo de produto adequado ao seu design, campanha, evento ou programa de varejo.", ar: "Select the product type that matches your artwork, campaign, event or retail program.", ja: "Select the product type that matches your artwork, campaign, event or retail program." },
  "Custom Lapel Pins": { de: "Individuelle Ansteckpins", fr: "Pins personnalises", es: "Pines personalizados", it: "Spille personalizzate", pt: "Pins personalizados", ar: "Custom Lapel Pins", ja: "Custom Lapel Pins" },
  "Challenge Coins": { de: "Challenge Coins", fr: "Challenge coins", es: "Challenge coins", it: "Challenge coin", pt: "Moedas challenge", ar: "Challenge Coins", ja: "Challenge Coins" },
  "Custom Medals": { de: "Individuelle Medaillen", fr: "Medailles personnalisees", es: "Medallas personalizadas", it: "Medaglie personalizzate", pt: "Medalhas personalizadas", ar: "Custom Medals", ja: "Custom Medals" },
  "Metal Keychains": { de: "Metall-Schluesselanhaenger", fr: "Porte-cles metalliques", es: "Llaveros metalicos", it: "Portachiavi metallici", pt: "Chaveiros metalicos", ar: "Metal Keychains", ja: "Metal Keychains" },
  "Belt Buckles": { de: "Guertelschnallen", fr: "Boucles de ceinture", es: "Hebillas de cinturon", it: "Fibbie per cinture", pt: "Fivelas de cinto", ar: "Belt Buckles", ja: "Belt Buckles" },
  "Bottle Openers": { de: "Flaschenoeffner", fr: "Decapsuleurs", es: "Abridores de botella", it: "Apribottiglie", pt: "Abridores de garrafa", ar: "Bottle Openers", ja: "Bottle Openers" },
  "Fridge Magnets": { de: "Kuehlschrankmagnete", fr: "Magnets de refrigerateur", es: "Imanes de nevera", it: "Magneti da frigo", pt: "Imas de geladeira", ar: "Fridge Magnets", ja: "Fridge Magnets" },
  "Cufflinks / Tie Clips": { de: "Manschettenknoepfe / Krawattenclips", fr: "Boutons de manchette / Pinces a cravate", es: "Gemelos / Clips de corbata", it: "Gemelli / Fermacravatte", pt: "Abotoaduras / Prendedores de gravata", ar: "Cufflinks / Tie Clips", ja: "Cufflinks / Tie Clips" },
  "Golf Ball Markers / Hat Clips": { de: "Golfballmarker / Hutclips", fr: "Marqueurs de golf / Clips de casquette", es: "Marcadores de golf / Clips para gorra", it: "Marcatori golf / Clip cappello", pt: "Marcadores de golf / Clips de chapeu", ar: "Golf Ball Markers / Hat Clips", ja: "Golf Ball Markers / Hat Clips" },
  "Enamel, die struck and printed pins": { de: "Emaille-, Prage- und Druckpins", fr: "Pins emailles, frappes et imprimes", es: "Pines esmaltados, troquelados e impresos", it: "Spille smaltate, coniate e stampate", pt: "Pins esmaltados, cunhados e impressos", ar: "Enamel, die struck and printed pins", ja: "Enamel, die struck and printed pins" },
  "2D and 3D commemorative coins": { de: "2D- und 3D-Gedenkmunzen", fr: "Pieces commemoratives 2D et 3D", es: "Monedas conmemorativas 2D y 3D", it: "Monete commemorative 2D e 3D", pt: "Moedas comemorativas 2D e 3D", ar: "2D and 3D commemorative coins", ja: "2D and 3D commemorative coins" },
  "Sports, school and event medals": { de: "Medaillen fur Sport, Schule und Events", fr: "Medailles sportives, scolaires et evenementielles", es: "Medallas deportivas, escolares y de eventos", it: "Medaglie per sport, scuola ed eventi", pt: "Medalhas para esporte, escola e eventos", ar: "Sports, school and event medals", ja: "Sports, school and event medals" },
  "Promotional and retail keychains": { de: "Werbe- und Retail-Schluesselanhaenger", fr: "Porte-cles promotionnels et retail", es: "Llaveros promocionales y retail", it: "Portachiavi promozionali e retail", pt: "Chaveiros promocionais e de varejo", ar: "Promotional and retail keychains", ja: "Promotional and retail keychains" },
  "Premium zinc alloy buckles": { de: "Hochwertige Zinklegierungs-Schnallen", fr: "Boucles premium en alliage de zinc", es: "Hebillas premium de aleacion de zinc", it: "Fibbie premium in lega di zinco", pt: "Fivelas premium em liga de zinco", ar: "Premium zinc alloy buckles", ja: "Premium zinc alloy buckles" },
  "Souvenir and promotional magnets": { de: "Souvenir- und Werbemagnete", fr: "Magnets souvenir et promotionnels", es: "Imanes souvenir y promocionales", it: "Magneti souvenir e promozionali", pt: "Imas promocionais e de lembranca", ar: "Souvenir and promotional magnets", ja: "Souvenir and promotional magnets" },
  "Custom Coins, Pins & Metal Crafts": { de: "Individuelle Coins, Pins & Metallwaren", fr: "Pieces, pins et objets metalliques personnalises", es: "Monedas, pines y artesanias metalicas personalizadas", it: "Monete, spille e articoli metallici personalizzati", pt: "Moedas, pins e brindes metalicos personalizados", ar: "Custom Coins, Pins & Metal Crafts", ja: "Custom Coins, Pins & Metal Crafts" },
  "Factory-direct OEM and ODM custom metal gifts for USA, Europe and Middle East buyers, backed by 20+ years of production experience and industrial-grade QC.": { de: "Werksdirekte OEM- und ODM-Metallgeschenke fur Kaufer in den USA, Europa und dem Nahen Osten, gestutzt auf uber 20 Jahre Produktionserfahrung und industrielle Qualitatskontrolle.", fr: "Cadeaux metalliques OEM et ODM en direct usine pour les acheteurs aux Etats-Unis, en Europe et au Moyen-Orient, avec plus de 20 ans d'experience et un controle qualite industriel.", es: "Regalos metalicos OEM y ODM directos de fabrica para compradores de EE. UU., Europa y Medio Oriente, respaldados por mas de 20 anos de experiencia y control de calidad industrial.", it: "Regali metallici OEM e ODM diretti dalla fabbrica per buyer USA, Europa e Medio Oriente, con oltre 20 anni di esperienza produttiva e QC industriale.", pt: "Brindes metalicos OEM e ODM direto da fabrica para compradores dos EUA, Europa e Oriente Medio, com mais de 20 anos de experiencia e controle de qualidade industrial.", ar: "Factory-direct OEM and ODM custom metal gifts for USA, Europe and Middle East buyers, backed by 20+ years of production experience and industrial-grade QC.", ja: "Factory-direct OEM and ODM custom metal gifts for USA, Europe and Middle East buyers, backed by 20+ years of production experience and industrial-grade QC." },
  "Free Design": { de: "Kostenloses Design", fr: "Design gratuit", es: "Diseno gratuito", it: "Design gratuito", pt: "Design gratuito", ar: "Free Design", ja: "Free Design" },
  "Factory Direct": { de: "Direkt ab Werk", fr: "Direct usine", es: "Directo de fabrica", it: "Diretto dalla fabbrica", pt: "Direto da fabrica", ar: "Factory Direct", ja: "Factory Direct" },
  "OEM & ODM": { de: "OEM & ODM", fr: "OEM & ODM", es: "OEM y ODM", it: "OEM e ODM", pt: "OEM e ODM", ar: "OEM & ODM", ja: "OEM & ODM" },
  "Global Delivery": { de: "Weltweite Lieferung", fr: "Livraison mondiale", es: "Entrega global", it: "Consegna globale", pt: "Entrega global", ar: "Global Delivery", ja: "Global Delivery" },
  "Professional design support before sampling.": { de: "Professionelle Designunterstutzung vor der Bemusterung.", fr: "Support design professionnel avant l'echantillonnage.", es: "Soporte profesional de diseno antes del muestreo.", it: "Supporto design professionale prima del campione.", pt: "Suporte profissional de design antes da amostra.", ar: "Professional design support before sampling.", ja: "Professional design support before sampling." },
  "Vertical production with stable quality control.": { de: "Vertikale Produktion mit stabiler Qualitatskontrolle.", fr: "Production integree avec controle qualite stable.", es: "Produccion vertical con control de calidad estable.", it: "Produzione verticale con controllo qualita stabile.", pt: "Producao vertical com controle de qualidade estavel.", ar: "Vertical production with stable quality control.", ja: "Vertical production with stable quality control." },
  "Custom materials, finishes, accessories and packaging.": { de: "Individuelle Materialien, Oberflachen, Zubehor und Verpackungen.", fr: "Materiaux, finitions, accessoires et emballages personnalises.", es: "Materiales, acabados, accesorios y embalajes personalizados.", it: "Materiali, finiture, accessori e packaging personalizzati.", pt: "Materiais, acabamentos, acessorios e embalagens personalizados.", ar: "Custom materials, finishes, accessories and packaging.", ja: "Custom materials, finishes, accessories and packaging." },
  "Export support for USA, Europe and Middle East orders.": { de: "Exportservice fur Auftrage aus den USA, Europa und dem Nahen Osten.", fr: "Support export pour les commandes USA, Europe et Moyen-Orient.", es: "Soporte de exportacion para pedidos de EE. UU., Europa y Medio Oriente.", it: "Supporto export per ordini USA, Europa e Medio Oriente.", pt: "Suporte de exportacao para pedidos dos EUA, Europa e Oriente Medio.", ar: "Export support for USA, Europe and Middle East orders.", ja: "Export support for USA, Europe and Middle East orders." },
  "Our Products": { de: "Unsere Produkte", fr: "Nos produits", es: "Nuestros productos", it: "I nostri prodotti", pt: "Nossos produtos", ar: "Our Products", ja: "Our Products" },
  "Core custom metal products for importers, brands, events and institutional buyers.": { de: "Kernprodukte aus Metall fur Importeure, Marken, Events und institutionelle Kaufer.", fr: "Produits metalliques personnalises pour importateurs, marques, evenements et acheteurs institutionnels.", es: "Productos metalicos personalizados para importadores, marcas, eventos y compradores institucionales.", it: "Prodotti metallici personalizzati per importatori, brand, eventi e buyer istituzionali.", pt: "Produtos metalicos personalizados para importadores, marcas, eventos e compradores institucionais.", ar: "Core custom metal products for importers, brands, events and institutional buyers.", ja: "Core custom metal products for importers, brands, events and institutional buyers." },
  "Download Catalog": { de: "Katalog herunterladen", fr: "Telecharger le catalogue", es: "Descargar catalogo", it: "Scarica catalogo", pt: "Baixar catalogo", ar: "Download Catalog", ja: "Download Catalog" },
  "Submit Inquiry": { de: "Anfrage senden", fr: "Envoyer la demande", es: "Enviar consulta", it: "Invia richiesta", pt: "Enviar consulta", ar: "Submit Inquiry", ja: "Submit Inquiry" },
  "Name": { de: "Name", fr: "Nom", es: "Nombre", it: "Nome", pt: "Nome", ar: "Name", ja: "Name" },
  "Email": { de: "E-Mail", fr: "E-mail", es: "Correo electronico", it: "Email", pt: "E-mail", ar: "Email", ja: "Email" },
  "Country": { de: "Land", fr: "Pays", es: "Pais", it: "Paese", pt: "Pais", ar: "Country", ja: "Country" },
  "Product Type": { de: "Produkttyp", fr: "Type de produit", es: "Tipo de producto", it: "Tipo di prodotto", pt: "Tipo de produto", ar: "Product Type", ja: "Product Type" },
  "Quantity": { de: "Menge", fr: "Quantite", es: "Cantidad", it: "Quantita", pt: "Quantidade", ar: "Quantity", ja: "Quantity" },
  "Deadline": { de: "Termin", fr: "Delai", es: "Fecha limite", it: "Scadenza", pt: "Prazo", ar: "Deadline", ja: "Deadline" },
  "Artwork Upload": { de: "Artwork hochladen", fr: "Televerser le visuel", es: "Subir arte", it: "Carica artwork", pt: "Enviar arte", ar: "Artwork Upload", ja: "Artwork Upload" },
  "Message": { de: "Nachricht", fr: "Message", es: "Mensaje", it: "Messaggio", pt: "Mensagem", ar: "Message", ja: "Message" },
  "Company": { de: "Unternehmen", fr: "Entreprise", es: "Empresa", it: "Azienda", pt: "Empresa", ar: "Company", ja: "Company" },
  "About & Factory": { de: "Uber uns & Fabrik", fr: "A propos & usine", es: "Sobre nosotros y fabrica", it: "Chi siamo e fabbrica", pt: "Sobre nos e fabrica", ar: "About & Factory", ja: "About & Factory" },
  "Contact Information": { de: "Kontaktinformationen", fr: "Coordonnees", es: "Informacion de contacto", it: "Informazioni di contatto", pt: "Informacoes de contato", ar: "Contact Information", ja: "Contact Information" },
  "CONTACT INFORMATION": { de: "KONTAKTINFORMATIONEN", fr: "COORDONNEES", es: "INFORMACION DE CONTACTO", it: "INFORMAZIONI DI CONTATTO", pt: "INFORMACOES DE CONTATO", ar: "CONTACT INFORMATION", ja: "CONTACT INFORMATION" },
  "Open in OpenStreetMap": { de: "In OpenStreetMap oeffnen", fr: "Ouvrir dans OpenStreetMap", es: "Abrir en OpenStreetMap", it: "Apri in OpenStreetMap", pt: "Abrir no OpenStreetMap", ar: "Open in OpenStreetMap", ja: "Open in OpenStreetMap" },
  "Visit or contact Unique Pin": { de: "Besuchen oder kontaktieren Sie Unique Pin", fr: "Visitez ou contactez Unique Pin", es: "Visite o contacte a Unique Pin", it: "Visita o contatta Unique Pin", pt: "Visite ou contate a Unique Pin", ar: "Visit or contact Unique Pin", ja: "Visit or contact Unique Pin" },
  "A real factory address and clear contact route help overseas buyers verify supplier identity before placing OEM and ODM orders.": { de: "Eine echte Fabrikadresse und klare Kontaktwege helfen internationalen Kaufern, den Lieferanten vor OEM- und ODM-Bestellungen zu prufen.", fr: "Une adresse d'usine reelle et un contact clair aident les acheteurs internationaux a verifier le fournisseur avant commande OEM et ODM.", es: "Una direccion real de fabrica y una ruta de contacto clara ayudan a verificar al proveedor antes de pedidos OEM y ODM.", it: "Un indirizzo reale della fabbrica e contatti chiari aiutano i buyer esteri a verificare il fornitore prima degli ordini OEM e ODM.", pt: "Um endereco real de fabrica e contatos claros ajudam compradores internacionais a verificar o fornecedor antes de pedidos OEM e ODM.", ar: "A real factory address and clear contact route help overseas buyers verify supplier identity before placing OEM and ODM orders.", ja: "A real factory address and clear contact route help overseas buyers verify supplier identity before placing OEM and ODM orders." },
  "Zhongshan Unique Metal Gift Co., LTD provides OEM and ODM custom metal crafts for importers, brands, event teams and institutional buyers.": { de: "Zhongshan Unique Metal Gift Co., LTD liefert OEM- und ODM-Metallwaren fur Importeure, Marken, Eventteams und institutionelle Kaufer.", fr: "Zhongshan Unique Metal Gift Co., LTD fournit des objets metalliques OEM et ODM aux importateurs, marques, equipes evenementielles et acheteurs institutionnels.", es: "Zhongshan Unique Metal Gift Co., LTD ofrece artesanias metalicas OEM y ODM para importadores, marcas, eventos y compradores institucionales.", it: "Zhongshan Unique Metal Gift Co., LTD fornisce articoli metallici OEM e ODM per importatori, brand, eventi e buyer istituzionali.", pt: "Zhongshan Unique Metal Gift Co., LTD fornece brindes metalicos OEM e ODM para importadores, marcas, eventos e compradores institucionais.", ar: "Zhongshan Unique Metal Gift Co., LTD provides OEM and ODM custom metal crafts for importers, brands, event teams and institutional buyers.", ja: "Zhongshan Unique Metal Gift Co., LTD provides OEM and ODM custom metal crafts for importers, brands, event teams and institutional buyers." }
};

export function getTranslation(source: string, language: LanguageCode) {
  if (language === "en") return source;
  return phraseTable[source]?.[language] || source;
}

export function findSourceFromAnyLanguage(text: string) {
  if (phraseTable[text]) return text;
  for (const [source, translations] of Object.entries(phraseTable)) {
    if (Object.values(translations).includes(text)) return source;
  }
  return text;
}
